 Tue, 17 Mar 2020 23:04:42  INFO test_login.py setUpClass [ line:39 ] ==================== 准备开始执行登录接口测试 ====================
 Tue, 17 Mar 2020 23:04:42  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login，请求参数：{'mobilephone': '#login_phone1#', 'pwd': '#pwd1#'}
 Tue, 17 Mar 2020 23:04:42  DEBUG connectionpool.py _new_conn [ line:225 ] Starting new HTTP connection (1): 118.24.221.133:8081
 Tue, 17 Mar 2020 23:04:42  DEBUG connectionpool.py _make_request [ line:437 ] http://118.24.221.133:8081 "POST /futureloan/mvc/api/member/login HTTP/1.1" 200 None
 Tue, 17 Mar 2020 23:04:42  ERROR test_login.py test_login [ line:67 ] {'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'} != {'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'}
- {'code': '20111', 'data': None, 'msg': '用户名或密码错误', 'status': 0}
?           ^ ^^                          ^^^^^^^^             ^

+ {'code': '10001', 'data': None, 'msg': '登录成功', 'status': 1}
?           ^ ^^                          ^^^^             ^
Traceback (most recent call last):
  File "/Users/yangli/PycharmProjects/api_course/test_cases/test_login.py", line 64, in test_login
    self.assertEqual(res, eval(case.expected_data))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'} != {'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'}
- {'code': '20111', 'data': None, 'msg': '用户名或密码错误', 'status': 0}
?           ^ ^^                          ^^^^^^^^             ^

+ {'code': '10001', 'data': None, 'msg': '登录成功', 'status': 1}
?           ^ ^^                          ^^^^             ^

 Tue, 17 Mar 2020 23:04:42  INFO test_login.py tearDownClass [ line:44 ] ==================== 登录接口测试执行完毕 ====================
